package com.agilerules.iotled.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "led_details")

/**
 * This class holds the LED Model attributes
 *
 */
public class LedModel {
	
	// An autogenerated id (unique for each user in the db)
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "ID")
	private long id;
	@Column(name = "BlinkStatus")
	private String blinkStatus;
	@Column(name = "DateTimeStamp")
	private String dateTimeStamp;
	@Column(name = "BlinkCounter")
	private int blinkCounter;
	@Column(name = "JsonPayload")
	private String jsonPayload;
	
	 
	public long getId() {
		return id;
	}
	public void setId(long id) {
		this.id = id;
	}
	
	public String getBlinkStatus() {
		return blinkStatus;
	}
	public void setBlinkStatus(String blinkStatus) {
		this.blinkStatus = blinkStatus;
	}
	public String getDateTimeStamp() {
		return dateTimeStamp;
	}
	public void setDateTimeStamp(String dateTimeStamp) {
		this.dateTimeStamp = dateTimeStamp;
	}
	public int getBlinkCounter() {
		return blinkCounter;
	}
	public void setBlinkCounter(int blinkCounter) {
		this.blinkCounter = blinkCounter;
	}
	public String getJsonPayload() {
		return jsonPayload;
	}
	public void setJsonPayload(String jsonPayload) {
		this.jsonPayload = jsonPayload;
	}
	
}
